### ISSUE TITLE
When using ParticleRenderer,  white border appears around particle.

### ISSUE THREAD

**Issue by yinxing-ws** [oasis-engine/engine#125]
**Describe the bug**
It looks like this: 
![image](https://user-images.githubusercontent.com/20393433/112601021-deb51480-8e4c-11eb-9987-317def7f1e54.png)

I'm not sure this problem is about the png image I use or  the render system.
Here is the image I use:  https://gw.alipayobjects.com/zos/gltf-asset/mars-cli/QUTYGTEWBLYN/1622456348-b6060.png
And Here is my code: 
![image](https://user-images.githubusercontent.com/20393433/112601274-3b183400-8e4d-11eb-8176-e1363f01c5b8.png)

**To Reproduce**
Just use ParticleRenderer and set texture to the image above.

**Expected behavior**
White border should not appear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: iphone and android

**Additional context**
Something may be helpful: The same problem appears on @alipay/mars-player (I dont remeber specific version), but the latest version has fixed this.

**Comment by GuoLei1990** [comment]
We has fix this bug with https://github.com/oasis-engine/engine/pull/127

**Comment by GuoLei1990** [comment]
If there is no relevant report for version 0.3, we will close this issue later.
