### ISSUE TITLE
加载 3d buidler创建的模型尺寸问题

### ISSUE THREAD

**Issue by edgexie** [oasis-engine/engine#142]
我用win10带的 `3d builder` 创建的 gltf 模型，单位是米，请问用 oasis 加载进来，尺寸是怎么换算的?

**Comment by GuoLei1990** [comment]
通常建模软件会有一定尺寸比例，如果建模软件导出时可以设置1坐标单位=1米的话。我们也会期望导入到Oasis中保持这个比例。也就是你创建了10米的长度模型等于Oasis 10个坐标单位。这样你就可以假设Oasis中的坐标单位也是米。
