### ISSUE TITLE
渲染流程上的一些问题

### ISSUE THREAD

**Issue by zhoumingyang** [oasis-engine/engine#143]
只有在swithRenderCount或者switchProgram时才会去重新绑定纹理，对于不同纹理的renderElement，在相同pipeline下，会不会出现每帧只绑定第1个渲染物体的材质，导致纹理渲染对不上问题

**Comment by GuoLei1990** [comment]
We have fixed with https://github.com/oasis-engine/engine/pull/148/files.
Thank you to report this bug and provide clues.


We will thank you in milestone PR.
