### ISSUE TITLE
package.json 配置

### ISSUE THREAD

**Issue by FuzzyFade** [oasis-engine/engine#17]
![image](https://user-images.githubusercontent.com/25416941/106439622-dbd41e00-64b2-11eb-9f43-22854afc1dfc.png)
这里要注意一下呀，而且还没有 license

**Comment by gz65555** [comment]
monorepo 根目录的 package.json 都是 private 的，表示根目录不需要发包。

**Comment by FuzzyFade** [comment]
> monorepo 根目录的 package.json 都是 private 的，表示根目录不需要发包。

是的，好久没写忘记了
