### ISSUE TITLE
在Vue中使用Script组件报错

### ISSUE THREAD

**Issue by LinsRock** [oasis-engine/engine#229]
**Describe the bug**
在Vue中使用到Script组件时，会报一个错误，是否不能在Vue中使用oasis-engine呢？
![image](https://user-images.githubusercontent.com/24631029/114966510-4804d200-9ea5-11eb-9cd9-dccf71e03a2d.png)

"@oasis-engine/controls": "0.3.2",
    "dat.gui": "0.7.7",
    "oasis-engine": "0.3.2",
    "vue": "^2.6.11"

**To Reproduce**
[演示地址](https://codesandbox.io/s/naughty-monad-0z3ji?file=/src/components/Demo2.vue&resolutionWidth=414&resolutionHeight=717)

**Expected behavior**
可以在Vue中使用Script，不报错

**Code**
```vue
<template>
  <div class="container">
    <canvas id="demo2" />
  </div>
</template>

<script>
import {
  AmbientLight,
  WebGLEngine,
  Script,
  Camera,
  Vector3,
} from "oasis-engine";

class ResourceScript extends Script {
  async onAwake() {
    const gltf = await this.engine.resourceManager.load(
      "https://gw.alipayobjects.com/os/OasisHub/c11f06c1-12b4-447f-a7c4-c75ba7f692f4/86/0.46107136414206873.gltf"
    );
    gltf.defaultSceneRoot.transform.setPosition(0, -10, 0);
    this.entity.addChild(gltf.defaultSceneRoot);
  }
}

export default {
  mounted() {
    this.init();
  },
  methods: {
    init() {
      // 创建画布
      const engine = new WebGLEngine("demo2");
      // 设置屏幕适配
      engine.canvas.resizeByClientSize();

      const rootEntity = engine.sceneManager.activeScene.createRootEntity();

      const cameraEntity = rootEntity.createChild("camera");
      cameraEntity.addComponent(Camera);
      const pos = cameraEntity.transform.position;
      pos.setValue(0, -5, 20);
      cameraEntity.transform.position = pos;
      cameraEntity.transform.lookAt(new Vector3(0, -5, 0));

      rootEntity.addComponent(ResourceScript);
      let ambientLight = rootEntity.addComponent(AmbientLight);
      ambientLight.intensity = 1.2;

      engine.run();
    },
  },
};
</script>
```

**Comment by eyworldwide** [comment]
It seems there is a babel config problem. I will look into it.

**Comment by eyworldwide** [comment]
@LinsRock You can try [create-oasis-app](https://github.com/oasis-engine/create-oasis-app) which can create oasis app with vue framework.

**Comment by LinsRock** [comment]
> @LinsRock You can try [create-oasis-app](https://github.com/oasis-engine/create-oasis-app) which can create oasis app with vue framework.

暂时只能在Vue3中使用么，不能在Vue2中使用吗？

**Comment by gz65555** [comment]
@LinsRock oasis 是个 js 的库，在 Vue2、Vue3 或者是 React 上都能跑。

这个应该是工程上（这个看起来是 codesandbox 或是 vue-cli 的问题）不支持**继承**的语法，直接加载 gltf 是可以成功的，可以参考这个：https://codesandbox.io/s/blazing-snowflake-98xtu?file=/src/components/Demo2.vue
