### ISSUE TITLE
Set canvas width and height by default

### ISSUE THREAD

**Issue by eyworldwide** [oasis-engine/engine#264]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I write the `Create engine` code that I have to set canvas width and height manually:
```typescript
  // Create engine
  const engine = new WebGLEngine("canvas");
  engine.canvas.width = canvas.clientWidth  * SystemInfo.devicePixelRatio;
  engine.canvas.height = canvas.clientHeight * SystemInfo.devicePixelRatio;
```

**Describe the solution you'd like**
Maybe these two lines of code can be included in `WebCanvas` class which can help me set canvas width and height by default. 

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by GuoLei1990** [comment]
After consideration, we think `resizeByClientSize` is the best choice
