### ISSUE TITLE
【请教】engine 开源代码是否包含 native runtime 部分？Alipay 小程序对接 oasis 的底层方式是什么？

### ISSUE THREAD

**Issue by kenkozheng** [oasis-engine/engine#27]
感谢 oasis 团队给大家带来这个高效引擎。

小弟学习之中有一些疑问。
engine 开源代码是否包含 native runtime 部分？Alipay 小程序对接 oasis 的底层方式是什么？

**Comment by singlecoder** [comment]
> 感谢 oasis 团队给大家带来这个高效引擎。
> 
> 小弟学习之中有一些疑问。
> engine 开源代码是否包含 native runtime 部分？Alipay 小程序对接 oasis 的底层方式是什么？

你好，目前我们引擎还没有对 native 的支持，后续有这方面的规划。小程序适配这块近期我们会和大家分享的，具体时间看 @gz65555

**Comment by gz65555** [comment]
1. 没包含 native runtime 的部分。
2. 只是小程序底层暴露对应的标准 WebGL API 提供给 Oasis 进行对接，然后 Oasis 的 js 运行环境对接到小程序的运行环境。
3. 后面会有文章去做解析。

**Comment by gz65555** [comment]
@kenkozheng 有问题可以继续问，这个 issue 先关了。
