### ISSUE TITLE
A dependency error occurred when I tried to bootstrap the project with "npm run bootstrap"

### ISSUE THREAD

**Issue by Mcnwork2018** [oasis-engine/engine#276]
**Describe the bug**
A dependency error occurred when I tried to bootstrap the project with "npm run bootstrap"

**To Reproduce**

1. git clone git@github.com:oasis-engine/engine.git
2. open terminal , input  `npm run bootstrap`

**Expected behavior**
Normal boot

**Screenshots**
<img width="546" alt="npm error" src="https://user-images.githubusercontent.com/37660444/118071550-950f9180-b3da-11eb-966e-fa969f896d2f.png">

**Desktop (please complete the following information):**
 - OS: Windows_NT 10.0.19042
 - node.js version:  v16.0.0
 - npm version: v7.10.0

**Additional context**
1. When I try to add `--fore` or `--legacy-peer-deps` after `npm i` in `package.json => scripts =>bootstrap`, the problem is solved.
2. We can see from the error log that there is a problem with `jest-electron` and dependency on `jest`.

**Comment by gz65555** [comment]
fixed.
