### ISSUE TITLE
Mobile Material Enhancement

### ISSUE THREAD

**Issue by gz65555** [oasis-engine/engine#29]
refactor `UnlitMaterial` and `BlinnPhongMaterial`, clean up shaderlib.

**Comment by zhuxudong** [comment]
### UnlightMaterial
- [ ] AlphaMode.Cutoff
- [ ] ambient logic

### BinnPhongMaterial
- [ ] AlphaMode.Cutoff
- [ ] normalTexture
- [ ] abstract normal plugin-in `OES_standard_derivatives`
- [ ] occlusionTexture
- [ ] opacity

### shaderLib Clean Up

**Comment by zhuxudong** [comment]
### UnlitMaterial
- [x] AlphaMode.Cutoff
- [ ] ambient logic

### BinnPhongMaterial
- [x] AlphaMode.Cutoff
- [ ] normalTexture
- [ ] abstract normal plugin-in `OES_standard_derivatives`
- [ ] occlusionTexture
- [ ] opacity

### shaderLib Clean Up
- [x] clipplane
