### ISSUE TITLE
glb模型的贴图加载不正常

### ISSUE THREAD

**Issue by InvictusNightmares** [oasis-engine/engine#292]
**Describe the bug**
glb模型加载样式不正常，部分贴图加载不出来，用threejs可以正常加载，不知道什么原因，求帮助！

**Screenshots**
oasis加载截图:
![image](https://user-images.githubusercontent.com/15864222/118830639-b21ff500-b8f1-11eb-8279-06f4b4f0975a.png)
![image](https://user-images.githubusercontent.com/15864222/118830686-b5b37c00-b8f1-11eb-8124-85fb6caf1582.png)
![image](https://user-images.githubusercontent.com/15864222/118830702-b9470300-b8f1-11eb-80ca-a621f449978a.png)
![image](https://user-images.githubusercontent.com/15864222/118830715-bba95d00-b8f1-11eb-88a8-4441b3fd2057.png)
![image](https://user-images.githubusercontent.com/15864222/118830731-be0bb700-b8f1-11eb-8d1b-b2ad4f4af7af.png)
![image](https://user-images.githubusercontent.com/15864222/118830747-c06e1100-b8f1-11eb-92e9-c0b971507b5b.png)

threejs加载截图:
![image](https://user-images.githubusercontent.com/15864222/118831335-468a5780-b8f2-11eb-8612-d13411fbdd08.png)
![image](https://user-images.githubusercontent.com/15864222/118831344-48ecb180-b8f2-11eb-888b-9897108bd4c2.png)
![image](https://user-images.githubusercontent.com/15864222/118831357-4b4f0b80-b8f2-11eb-8cd8-1bd72855899c.png)
![image](https://user-images.githubusercontent.com/15864222/118831396-543fdd00-b8f2-11eb-85b0-9774c774cbdc.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 0.3.11

**Comment by zhuxudong** [comment]
麻烦提供一下模型~

**Comment by InvictusNightmares** [comment]
> 麻烦提供一下模型~

[untitled.gltf.zip](https://github.com/oasis-engine/engine/files/6509827/untitled.gltf.zip)

**Comment by zhuxudong** [comment]
@InvictusNightmares 具体的原因是 gltf loader 错误地处理了 texture 为 image：[代码](https://github.com/oasis-engine/engine/blob/main/packages/loader/src/GLTFLoader.ts#L98)。

我们已经在 #257 中对 GLTF Loader 进行了全面的重构，其中修复了这个问题，并跑通了 khronos 官网的所有测试案例：https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0 

有三种解决方法：您可以等待 oasis 0.4 的发布；或者更改 GLTF 文件增加 image 字段临时兼容一下；或者在代码中手动给材质赋予相应的纹理。造成的不便，感到非常抱歉。

![image](https://user-images.githubusercontent.com/17639043/118854415-4ba5d180-b907-11eb-914e-f34026903a6b.png)
![image](https://user-images.githubusercontent.com/17639043/118854751-9cb5c580-b907-11eb-8b18-de6276db5437.png)

**Comment by InvictusNightmares** [comment]
@zhuxudong 
您好，想请教一下关于这段“更改 GLTF 文件修改 image、texture 字段临时兼容一下”具体是怎么处理的吗？

**Comment by zhuxudong** [comment]
> @zhuxudong
> 您好，想请教一下关于这段“更改 GLTF 文件修改 image、texture 字段临时兼容一下”具体是怎么处理的吗？

参考给您的附件中的 texture 字段

**Comment by InvictusNightmares** [comment]
> > @zhuxudong
> > 您好，想请教一下关于这段“更改 GLTF 文件修改 image、texture 字段临时兼容一下”具体是怎么处理的吗？
> 
> 参考给您的附件中的 texture 字段

好的，十分感谢！

**Comment by InvictusNightmares** [comment]
> > @zhuxudong
> > 您好，想请教一下关于这段“更改 GLTF 文件修改 image、texture 字段临时兼容一下”具体是怎么处理的吗？
> 
> 参考给您的附件中的 texture 字段

@zhuxudong 大佬，这个问题还是要请教下，我不是很清楚这块要怎么弄？我们用的blender建的模型，可以给我一张您那边blender对texture处理这块的截图吗？万分感谢！

**Comment by zhuxudong** [comment]
@InvictusNightmares 我这边并没有对 blender 进行操作，您的操作是符合 GLTF 标准的，问题是由于上面我说的引擎的 gltf-loader 的 bug。正如给您的附件中那样，我这边只是改了下 gltf 源文件，暂时绕过去了这个问题。

**Comment by InvictusNightmares** [comment]
> @InvictusNightmares 我这边并没有对 blender 进行操作，您的操作是符合 GLTF 标准的，问题是由于上面我说的引擎的 gltf-loader 的 bug。正如给您的附件中那样，我这边只是改了下 gltf 源文件，暂时绕过去了这个问题。
"我这边只是改了下 gltf 源文件，暂时绕过去了这个问题"请问这一步操作我要怎么做？我们还有好几个模型，我想都改一下。

**Comment by InvictusNightmares** [comment]
> @InvictusNightmares 我这边并没有对 blender 进行操作，您的操作是符合 GLTF 标准的，问题是由于上面我说的引擎的 gltf-loader 的 bug。正如给您的附件中那样，我这边只是改了下 gltf 源文件，暂时绕过去了这个问题。

"我这边只是改了下 gltf 源文件，暂时绕过去了这个问题"请问这一步操作我要怎么做？我们还有好几个模型，我想都改一下。

**Comment by zhuxudong** [comment]
@InvictusNightmares 我明天和团队商量下是否要为断融版本修复 bug；作为替代方案，你能否接受提供给你一个node脚本，运行一下，修复 gltf 文件

**Comment by InvictusNightmares** [comment]
> @InvictusNightmares 我明天和团队商量下是否要为断融版本修复 bug；作为替代方案，你能否接受提供给你一个node脚本，运行一下，修复 gltf 文件

可以，十分感谢!

**Comment by zhuxudong** [comment]
@InvictusNightmares 先用这个脚本转换下 gltf
[transform.zip](https://github.com/oasis-engine/engine/files/6519822/transform.zip)

**Comment by InvictusNightmares** [comment]
> @InvictusNightmares 先用这个脚本转换下 gltf
> [transform.zip](https://github.com/oasis-engine/engine/files/6519822/transform.zip)
测试没问题，十分感谢！

**Comment by InvictusNightmares** [comment]
@GuoLei1990 @zhuxudong 大佬们，还想咨询一个问题，请问绿洲支持淘宝小程序吗？有相关文档吗？

**Comment by InvictusNightmares** [comment]
@zhuxudong 你好 我现在遇到个问题在android和iOS下模型的样式不一样，ios下可以显示镜面材质，android下无法显示镜面材质。
android下：
![image](https://user-images.githubusercontent.com/15864222/119335354-d6e3e600-bcbe-11eb-829f-1bd8f7854674.png)
ios下：
![image](https://user-images.githubusercontent.com/15864222/119335378-df3c2100-bcbe-11eb-864d-2be9710aaf1a.png)
请问下这种情况怎么解决?

**Comment by zhuxudong** [comment]
哪份文件，我试试能不能复现

**Comment by InvictusNightmares** [comment]
> 哪份文件，我试试能不能复现

感谢回复，已经解决了！还想请教一个问题就是我之前问的，绿洲支持淘宝小程序吗？

**Comment by zhuxudong** [comment]
> > 哪份文件，我试试能不能复现
> 
> 感谢回复，已经解决了！还想请教一个问题就是我之前问的，绿洲支持淘宝小程序吗？

支持的。这个issue没有问题的话可以关闭了

**Comment by InvictusNightmares** [comment]
> > > 哪份文件，我试试能不能复现
> > 
> > 
> > 感谢回复，已经解决了！还想请教一个问题就是我之前问的，绿洲支持淘宝小程序吗？
> 
> 支持的。这个issue没有问题的话可以关闭了

请问有相关文档或者demo吗？我没有找到。只找到了这个：https://www.npmjs.com/package/@oasis-engine/miniprogram-adapter

**Comment by gz65555** [comment]
可以的，用 [create-oasis-app](https://github.com/oasis-engine/create-oasis-app) 创建小程序项目。在 `app.json` 里添加 `enableSkia` 的配置即可：
```json
{
   "pages": [
      "pages/index/index"  
    ],
   "window": {
      "defaultTitle": "My App",
      "enableSkia":"true"  
    } 
}
```
可以查看[淘宝开放平台](https://miniapp.open.taobao.com/docV3.htm?docId=118999&docType=1&tag=dev)。

**Comment by InvictusNightmares** [comment]
> 可以的，用 [create-oasis-app](https://github.com/oasis-engine/create-oasis-app) 创建小程序项目。在 `app.json` 里添加 `enableSkia` 的配置即可：
> 
> ```json
> {
>    "pages": [
>       "pages/index/index"  
>     ],
>    "window": {
>       "defaultTitle": "My App",
>       "enableSkia":"true"  
>     } 
> }
> ```
> 
> 可以查看[淘宝开放平台](https://miniapp.open.taobao.com/docV3.htm?docId=118999&docType=1&tag=dev)。

好的 谢谢
