### ISSUE TITLE
MeshRenderer and GeometryRenderer refactored

### ISSUE THREAD

**Issue by gz65555** [oasis-engine/engine#30]
Current status
- The engine currently includes MeshRenderer and GeometryRenderer, with repetitive concepts.
- The MeshRenderer  almost no function.

Solution
- Unify MeshRenderer and GeometryRenderer as MeshRender and add features.
- Adjust Mesh and BufferGeometry functions, even naming.
- Let both Mesh and BufferGeometry be accepted by MeshRenderer.
- May refactor  the Renderer class.

**Comment by GuoLei1990** [comment]
[x] Delete GeometryRenderer.
[x] Adjust Material function to Renderer.
[x] Rename BufferGeometry to Mesh, and rename Mesh to ModleMesh.
[ ]  Add more advanced function to ModleMesh.
