### ISSUE TITLE
淘宝小程序加载有问题

### ISSUE THREAD

**Issue by InvictusNightmares** [oasis-engine/engine#302]
Describe the bug
淘宝小程序加载有问题，在小程序模拟器上可以正常加载模型并且成功添加了OrbitControl手势。但是在真机上出现问题：
android: 无法加载，灰屏
ios: 可以正常加载，手势无法添加

代码是通过 create-oasis-app创建的，用了小程序调试工具均无报错，淘宝App也是最新版本。

Screenshots
小程序模拟器：

https://user-images.githubusercontent.com/15864222/119353487-8a57d500-bcd5-11eb-9189-60f1a33aef59.mp4

iOS:
![image](https://user-images.githubusercontent.com/15864222/119353519-9348a680-bcd5-11eb-945d-c2a9510dd8f0.png)

android:
![image](https://user-images.githubusercontent.com/15864222/119353546-993e8780-bcd5-11eb-8064-dae19c1c6f30.png)

代码:
![image](https://user-images.githubusercontent.com/15864222/119353583-a491b300-bcd5-11eb-9ff7-f51f2af3d10f.png)
![截屏2021-05-24 下午9 20 22](https://user-images.githubusercontent.com/15864222/119353765-e15daa00-bcd5-11eb-829d-83f7379f23b1.png)

Smartphone (please complete the following information):

Device: [iphoneXs Max]
OS: [iOS14.6]

Device: [onePlus 7T]
OS: [android 10]

**Comment by gz65555** [comment]
@InvictusNightmares 有项目工程发一下，建个 git，或者钉钉上发我？

**Comment by InvictusNightmares** [comment]
> @InvictusNightmares 有项目工程发一下，建个 git，或者钉钉上发我？

麻烦提供下您的钉钉账号，我加您

**Comment by gz65555** [comment]
@InvictusNightmares fxynsrj

**Comment by InvictusNightmares** [comment]
> @InvictusNightmares fxynsrj

已经加您了
