### ISSUE TITLE
Custom Asset Loader

### ISSUE THREAD

**Issue by gz65555** [oasis-engine/engine#31]
### Custom Asset File Encoder/Decoder

For the reason that we shall edit assets on our web editor, we use custom files of asset to replace glTF files.

- [ ] Texture2D
- [ ] TextureCube
- [ ] Material
- [ ] Mesh
- [ ] A Tool for generating encoder/decoder.

**Comment by JASONPANGGO** [comment]
Will the web editor be opensource?
