### ISSUE TITLE
SpriteRenderer Refactor

### ISSUE THREAD

**Issue by gz65555** [oasis-engine/engine#32]
### Problem
- [ ] The existing rendering process are unreasonable.
- [ ] Not enough performance.
- [ ] Loss of function.
### Solution
- [x] Refactor 2D  SpriteRenderer.
- [x] Optimize the underlying rendering pipeline.

**Comment by singlecoder** [comment]
### Problem
- [ ] The existing rendering process are unreasonable.
- [ ] Not enough performance.
- [ ] Loss of function.
### Solution
- [ ] Refactor 2D  SpriteRenderer.
- [ ] Optimize the underlying rendering pipeline.
