### ISSUE TITLE
可否增加一个视频天空盒的功能？

### ISSUE THREAD

**Issue by InvictusNightmares** [oasis-engine/engine#324]
如题，可否增加一个视频天空盒子的功能？

https://user-images.githubusercontent.com/15864222/121451013-57009000-c9cf-11eb-897d-941c83734ae9.mp4

**Comment by GuoLei1990** [comment]
Yes! In the next version 0.4 of the sky, the sky Mesh and sky texture will be initially opened, and the engine will no longer force the use of the “sky box mode”! This kind of actual sky rendering grid needs to use sky dome, combined with the video texture feature to achieve!

**Comment by zhuxudong** [comment]
refer to https://github.com/oasis-engine/oasis-engine.github.io/pull/293
