### ISSUE TITLE
Animation System Enhancement

### ISSUE THREAD

**Issue by gz65555** [oasis-engine/engine#35]
- [ ] Enhanced AnimationClip:  Add Hermite Interpolation, Add Splitting, Optimize API
- [ ] Optimize mix and crossFade
- [ ] Add Animator Component to realize state machine driven animation

**Comment by luzhuang** [comment]
- [ ] Enhanced AnimationClip:  Add Hermite Interpolation, Add Splitting, Optimize API
- [ ] Optimize mix and crossFade
- [ ] Add Animator Component to realize state machine driven animation
