### ISSUE TITLE
Using canvas as ImageSource problem

### ISSUE THREAD

**Issue by HypnosNova** [oasis-engine/engine#366]
**Describe the bug**
用canvas作为纹理贴图到物体上会全是黑色

**To Reproduce**
1. 新建一个canvas
2. canvas用2d上下文随便画个图
3. 将物体的material里的baseTexture.setImageSource(canvas)
4. 物体变成纯黑

**Expected behavior**
期望canvas上画的图贴图在物体上

**Screenshots**
![image](https://user-images.githubusercontent.com/7953802/124252823-39a97800-dadc-11eb-83a9-851075ca4ac6.png)
如图，我搞了个canvas就全部图红色。然后把canvas贴图到物体就会全黑

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 最新

**Additional context**
参考代码如下：
`
import {
	AssetType,
	BlinnPhongMaterial,
	Camera,
	MeshRenderer,
	PrimitiveMesh,
	Texture2D,
	Vector3,
	WebGLEngine,
} from "oasis-engine";

const engine = new WebGLEngine("canvas");
engine.canvas.resizeByClientSize();
const scene = engine.sceneManager.activeScene;
const rootEntity = scene.createRootEntity();

// init camera
const cameraEntity = rootEntity.createChild("camera");
cameraEntity.addComponent(Camera);
const pos = cameraEntity.transform.position;
pos.setValue(3, 3, 3);
cameraEntity.transform.position = pos;
cameraEntity.transform.lookAt(new Vector3(0, 0, 0));

// init light
scene.ambientLight.diffuseSolidColor.setValue(1, 1, 1, 1);
scene.ambientLight.diffuseIntensity = 1.2;

// init cube
const cubeEntity = rootEntity.createChild("cube");
const renderer = cubeEntity.addComponent(MeshRenderer);
const mtl = new BlinnPhongMaterial(engine);
const color = mtl.baseColor;
color.r = 1.0;
color.g = 1.0;
color.b = 1.0;
color.a = 1.0;
renderer.mesh = PrimitiveMesh.createCuboid(engine);
renderer.setMaterial(mtl);

engine.run();

// canvas贴图
let texture = new Texture2D(engine, 512, 512);
let canvas = document.createElement("canvas");
canvas.width = canvas.height = 512;
let ctx = canvas.getContext('2d');
ctx.fillStyle = "red";
ctx.fillRect(0, 0, 512, 512);
document.body.appendChild(canvas);

texture.setImageSource(canvas);
mtl.baseTexture = texture;
`

**Comment by GuoLei1990** [comment]
Can you try disable mipmap in Texture2D’s `constructor` or call `generateMipmaps()` after `setImageSource ()`.

**Comment by zhuxudong** [comment]
@HypnosNova you need call `texture.generateMipmaps()` after `texture.setImageSource()`

**Comment by HypnosNova** [comment]
解决了

**Comment by gz65555** [comment]
> @HypnosNova you need call `texture.generateMipmaps()` after `texture.setImageSource()`

我也感觉需要调用这个方法不太好理解
