### ISSUE TITLE
The PBR model is displayed incorrectly

### ISSUE THREAD

**Issue by cptbtptpbcptdtptp** [oasis-engine/engine#390]
![image](https://user-images.githubusercontent.com/7768919/125640026-cc115443-7cfe-4f32-b4e6-1144154b0422.png)

**Comment by cptbtptpbcptdtptp** [comment]
1.Open website：https://oasisengine.cn/0.4/docs/material-cn

**Comment by GuoLei1990** [comment]
This maybe a bug of `chrome`, because `safari` and `firefox` don't have and trigger only in webl2.0 mode .

Recurring URL：https://oasisengine.cn/0.4/docs/material-cn

chrome version: 92.0.4515.107 (x86_64)

**Comment by GuoLei1990** [comment]
I check it can already be rendered correctly
chrome version:101.0.4951.54
