### ISSUE TITLE
请教！0.1.0中 entity.addEventListener 在 0.2.0中应该如何调整

### ISSUE THREAD

**Issue by Summer-andy** [oasis-engine/engine#44]
### Question
       
在``` oasis-engine ``` 的版本为0.1.0中, entity上挂载了事件监听, 请问在 0.2.0中应该如何做调整？
   
### Environment

- **`Oasis` version**:  0.2.0

**Comment by Summer-andy** [comment]
是通过这种方法吗？

```js
import {  EventDispatcher} from 'oasis-engine';

 const eventDispatcher = new EventDispatcher(engine);
    eventDispatcher.on('rotate_start', () => {
      console.log('object');
    })
```

**Comment by zhuxudong** [comment]
@Summer-andy call `engine.on/dispatch`

**Comment by gz65555** [comment]
> 是通过这种方法吗？
> 
> ```js
>  import {  EventDispatcher } from 'oasis-engine';
> 
>  const eventDispatcher = new EventDispatcher(engine);
> 
>  eventDispatcher.on('rotate_start', () => {
>    console.log('object');
>  })
> ```

可以直接使用这种方式。也可以直接引用脚本调用方法。

**Comment by Summer-andy** [comment]
好的， 谢谢了 ~
