### ISSUE TITLE
A CLI for Oasis

### ISSUE THREAD

**Issue by gz65555** [oasis-engine/engine#45]
## Problem

Users need a template to create a project.

## Solution

Use [vite](https://github.com/vitejs/vite) as  a build tool. And we need:

- [x] A template for React Users.
- [x] A template for Vue Users.
- [x] A template for VanillaJS Users.
- [x] A CLI to create a project.

**Comment by MrKou47** [comment]
Try this: https://oclif.io/

**Comment by gz65555** [comment]
I use: https://github.com/cacjs/cac.

**Comment by gz65555** [comment]
The repo is: https://github.com/oasis-engine/create-oasis-app .
