### ISSUE TITLE
OrbitControls autoRotateSpeed property's semantic is not accurate

### ISSUE THREAD

**Issue by eyworldwide** [oasis-engine/engine#49]
### Expected Behavior

**OrbitControls** [autoRotateSpeed](https://github.com/oasis-engine/engine/blob/main/packages/controls/src/OrbitControl.ts#L31)  propertry is bigger and the rotation speed is faster.

### Current Behavior
`autoRotateSpeed` is smaller and the rotation speed is slower.

### Possible Solution
`autoRotateSpeed` is now actually the time takes for rotating 360 degrees, so there're two solutions for the issue:
1. Change the property name, such as `autoRotateLife`
2. Make the semantic accurate: how many degrees (or radians) rotate per second.

### Steps to Reproduce

easy to reproduce, just set the `autoRotateSpeed` value.

### Environment

- **`Oasis` version**: _e.g. 0.2.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. MacOS 10.15.7_
- **Running Example**: _url_

**Comment by zhuxudong** [comment]
solved
