### ISSUE TITLE
"npm run doc "  is error in win10

### ISSUE THREAD

**Issue by buglas** [oasis-engine/engine#50]
### Expected Behavior
I can run doc in win10

### Current Behavior
I can't run doc in win10

### Possible Solution
delete "rm && rm -rf doc && " in "rm && rm -rf doc && typedoc --options tools/typedoc/typedoc.js"

### Steps to Reproduce
npm run doc

### Environment

- **`Oasis` version**: 0.2.0
- **OS & Version**: win10

**Comment by eyworldwide** [comment]
The documentation source of Oasis Engine have been migrated to https://github.com/oasis-engine/oasis-engine.github.io
