### ISSUE TITLE
Iteration Plan for 0.7 Unit Tests

### ISSUE THREAD

**Issue by gz65555** [oasis-engine/engine#507]
@cptbtptpbcptdtptp 
- [ ] spriteAtlas
- [ ] InputManager

@zhuxudong 
- [ ] GLTFUtil
- [ ] extentions
- [ ] SkinnedMeshRenderer
- [ ] MeshRenderer

@luzhuang  
- [ ] Animator

@singlecoder 
- [ ] PrimitiveMesh
- [ ] Sprite

@yangfengzzz 
- [ ] StaticCollider
- [ ] DyamicCollider
- [ ] PhysicsManger

@GuoLei1990 
- [ ] ComponentCloner
- [ ] CloneManager

**Comment by GuoLei1990** [comment]
This issue is left over from 0.6. @gz65555  checks the unit tests that should be added in 0.7
