### ISSUE TITLE
GLB Render Error

### ISSUE THREAD

**Issue by gz65555** [oasis-engine/engine#616]
**Describe the bug**
file: https://gw.alipayobjects.com/os/bmw-prod/0e30227a-a420-4362-8132-ee8d6f9fac7c.glb

**To Reproduce**
use `https://oasisengine.cn/gltf-viewer` load glb.

**Expected behavior**
three.js
![image](https://user-images.githubusercontent.com/6926263/145789082-c2ec400b-0c92-4621-9f64-72fb0c3474a7.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/6926263/145789167-f1787937-341f-4d81-8231-2ad33a2cfe14.png)

**Comment by zhuxudong** [comment]
occlusion texture algorithm is wrong

**Comment by zhuxudong** [comment]
multiple uv channel is not supported in engine

**Comment by zhuxudong** [comment]
track #683,  and close it.
