### ISSUE TITLE
碰撞

### ISSUE THREAD

**Issue by 823639792** [oasis-engine/engine#633]
我看到demo中，碰撞都是穿透的，有没有办法把碰撞设置成为反弹的？

**Comment by Fzc09** [comment]
如果不加物理引擎，你要得效果应该是碰撞后直接停止动画，或者变成一个折射角度的动画，但是不管哪个都是业务逻辑，不应该是引擎能力；
如果加了物理引擎，物理引擎应该会自己帮你算

**Comment by 823639792** [comment]
@Fzc09 
就是这个demo

**Comment by Cleam** [comment]
@823639792 

是要[这种效果](https://github.com/Cleam/oasis-engine-demos#d1-%E7%89%A9%E7%90%86%E7%A2%B0%E6%92%9E%E7%A4%BA%E4%BE%8B)么？

**Comment by 823639792** [comment]
是的

**Comment by GuoLei1990** [comment]
reference: #639

**Comment by GuoLei1990** [comment]
0.7 will support DynamicCollider. For details, see:
https://github.com/oasis-engine/engine/pull/680
https://github.com/oasis-engine/engine/pull/700
