### ISSUE TITLE
normalize quaternion after operation

### ISSUE THREAD

**Issue by yangfengzzz** [oasis-engine/engine#665]
**Describe the bug**
quaternion must be normalized otherwise it contain the scale information which will make the further calculation wrong!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GuoLei1990** [comment]
Has solved in https://github.com/oasis-engine/engine/pull/693
