### ISSUE TITLE
 Hope to fix: Compatibility issues with PointerEvent.

### ISSUE THREAD

**Issue by cptbtptpbcptdtptp** [oasis-engine/engine#690]
![image](https://user-images.githubusercontent.com/7768919/157710459-d95e0917-7cd1-46d3-bf0b-3d21aaba67e0.png)
link to: [CanIUse](https://caniuse.com/?search=pointerevent)

**Comment by GuoLei1990** [comment]
https://github.com/oasis-engine/polyfill-pointer-event
- Write README use English
- Developer should write `PointerPolyfill.register(htmlCanvasElement);` is not good, you can modify class property to ignore this
