### ISSUE TITLE
OrbitControl.enableZoom 设置失效

### ISSUE THREAD

**Issue by LiuSuY** [oasis-engine/engine#776]
**Describe the bug**
准确来说不能算是一个bug, 但是在sandbox 中预览 OrbitControl.enableZoom 是可以实现禁止缩放的，作为一个新的tab页打开预览模型就可以被放大，似乎enableZoom 这个设置就失效了。

**To Reproduce**
1. 源代码 [Scroll down to '....'](https://codesandbox.io/s/nifty-faraday-1pzt6r?file=/src/App.vue)
2.预览demo [See error](https://1pzt6r.csb.app)

**Expected behavior**
希望在预览demo下 enableZoom 属性可以禁止模型的缩放

**Screenshots**
放大后的
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/25116549/166106756-c2a9d877-da57-4421-974e-f744f44d91d7.png">
正常的
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/25116549/166106789-24614a87-041b-47e9-a6d2-7070732ba03b.png">

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser: chrome
 - Version: 101.0.4951.41
 - oasis: 0.6.9

**Comment by susiwen8** [comment]
你应该是理解错 `enableZoom` 的含义了，它是是否可随手势或者鼠标滚轮放大缩小

**Comment by LiuSuY** [comment]
> 你应该是理解`enableZoom`错误含义的，它是否可以随了或者滚轮放大缩小

好的，谢谢。我想我应该通过js禁止网页缩放。

**Comment by susiwen8** [comment]
不是网页缩放，应该是自适应
