### ISSUE TITLE
编辑器操作方式

### ISSUE THREAD

**Issue by exment** [oasis-engine/engine#850]
现在编辑器还没有发布，但是看到文档里面写的编辑器操作方式，请问能否加上自定义，
实现类似blender或者godot的场景里面的操作方式，比如 https://www.bilibili.com/read/cv13419647
每个引擎和建模工具都不一样的操作来回切实在太累了。。。

**Comment by JujieX** [comment]
谢谢你对编辑器的关注！我们会考虑增加自定义快捷键的
