### ISSUE TITLE
加载一些复杂的模型会报错

### ISSUE THREAD

**Issue by BugDongDong** [oasis-engine/engine#96]
**Describe the bug**
加载一些复杂的模型会报错，这个复杂的模型 有很多可以拆分的子模型。
![image](https://user-images.githubusercontent.com/72009892/110056374-a82e3180-7d99-11eb-8e24-2e5c3f94fd42.png)

**To Reproduce**
1.创建一个加载脚本
`
const { animations, defaultSceneRoot } = await this.engine.resourceManager.load<GLTFResource>(
            'http://127.0.0.1:8000/gltf/mode.obj',
        )
`
2.运行，运行后不显示模型，且浏览器会提示报错。自绘的节点可以被渲染。

**Expected behavior**
我希望能有个加载模型的万能函数，或者准确的加载模型。

**Screenshots**
无

**Desktop (please complete the following information):**
 - OS: window
 - Browser chrome
 - Version 87.0.4280.141

**Additional context**
无

**Comment by GuoLei1990** [comment]
看后缀是OBJ格式的模式，我们目前暂时只支持GLTF格式的模型

**Comment by singlecoder** [comment]
> **Describe the bug**
> 加载一些复杂的模型会报错，这个复杂的模型 有很多可以拆分的子模型。
> ![image](https://user-images.githubusercontent.com/72009892/110056374-a82e3180-7d99-11eb-8e24-2e5c3f94fd42.png)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1.创建一个加载脚本
> `const { animations, defaultSceneRoot } = await this.engine.resourceManager.load<GLTFResource>( 'http://127.0.0.1:8000/gltf/mode.obj', )`
> 2.运行，运行后不显示模型，且浏览器会提示报错。自绘的节点可以被渲染。
> 
> **Expected behavior**
> 我希望能有个加载模型的万能函数，或者准确的加载模型。
> 
> **Screenshots**
> 无
> 
> **Desktop (please complete the following information):**
> 
> * OS: window
> * Browser chrome
> * Version 87.0.4280.141
> 
> **Additional context**
> 无

**Comment by BugDongDong** [comment]
是的，但是通过格式转换成gltf还是无法加载。希望还是能尽快普及以下，gltf格式的模型主要是甲方bb用的，所以已经导致我转threejs了。这可能是一个新手入门的限制。

**Comment by GuoLei1990** [comment]
> 是的，但是通过格式转换成gltf还是无法加载。希望还是能尽快普及一下，gltf格式的模型主要是甲方bb用的，所以已经导致我转threejs了。这可能是一个新手入门的限制。

你好！请问方便吧转换后的 gltf 发给我们吗？我们想尝试一下解决这个问题

**Comment by GuoLei1990** [comment]
[door.glb.zip](https://github.com/oasis-engine/engine/files/6194474/door.glb.zip)
![Uploading image.png…]()
